name: Run Backend Tests

on:
  push:
    branches: [Dev]
  pull_request:
    branches: [Dev]

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  OPENIA_SECRET: ${{ secrets.OPENIA_SECRET }}
  ALGORITHM: ${{ secrets.ALGORITHM }}
  ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}


jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      python-path: ${{ steps.set-path.outputs.python-path }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Save PYTHONPATH
        id: set-path
        run: echo "python-path=$GITHUB_WORKSPACE" >> $GITHUB_OUTPUT

      - name: Upload workspace
        uses: actions/upload-artifact@v4
        with:
          name: backend-deps
          path: .

  user-tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: backend-deps
          path: .

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ needs.setup.outputs.python-path }}" >> $GITHUB_ENV

      - name: Run User Tests
        run: pytest tests/test_auth.py tests/test_user.py

  chatbot-tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: backend-deps
          path: .

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ needs.setup.outputs.python-path }}" >> $GITHUB_ENV

      - name: Run Chatbot Tests
        run: pytest tests/test_chat_flow.py
