name: Run Backend Tests

on:
  push:
    branches: [Dev]
  pull_request:
    branches: [Dev]

jobs:
  backend-tests:
    
    runs-on: ubuntu-latest
    
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      OPENIA_SECRET: ${{ secrets.OPENIA_SECRET }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

    - name: Run auth tests
      run: |
        echo "Running test_auth.py"
        pytest tests/test_auth.py

    - name: Run chat flow tests
      run: |
        echo "Running test_chat_flow.py"
        pytest tests/test_chat_flow.py

    - name: Run user tests
      run: |
        echo "Running test_user.py"
        pytest tests/test_user.py
